### ISSUE TITLE
fix like bug

### ISSUE THREAD

**Issue by doodzik** [doodzik/321157#7]

**Comment by hanansson** [comment]
https://www.youtube.com/watch?v=MsWJYm4GlAw&index=25&list=LLnhrr7Xsrl6TbG5UmdCa0Vw
https://www.youtube.com/watch?v=Ss0tGgEnFsU&list=LLnhrr7Xsrl6TbG5UmdCa0Vw&index=15
https://www.youtube.com/watch?v=qtG3YVGwUKs&list=LLnhrr7Xsrl6TbG5UmdCa0Vw&index=13
https://www.youtube.com/watch?v=Mc4flssYMas&list=LLnhrr7Xsrl6TbG5UmdCa0Vw&index=10&pxtry=1

**Comment by doodzik** [comment]
https://www.youtube.com/watch?v=qtG3YVGwUKs&list=LLnhrr7Xsrl6TbG5UmdCa0Vw&index=13

funktioniert jetzt. 
noch:

https://www.youtube.com/watch?v=MsWJYm4GlAw&index=25&list=LLnhrr7Xsrl6TbG5UmdCa0Vw
https://www.youtube.com/watch?v=Ss0tGgEnFsU&list=LLnhrr7Xsrl6TbG5UmdCa0Vw&index=15
https://www.youtube.com/watch?v=Mc4flssYMas&list=LLnhrr7Xsrl6TbG5UmdCa0Vw&index=10&pxtry=1
